### ISSUE TITLE
Lack go native testing on Authorizer and Filter role

### ISSUE THREAD

**Issue by yookoala** [yookoala/gofast#21]
The testing on Authorizer and Filter depends on node-fastcgi.

It would be preferable to have golang native testing. We, however, cannot depend on the [net/http/fcgi](https://golang.org/pkg/net/http/fcgi/) library because it only implemented the Responder role. Helps to resolve #2.

**TODO**
- [ ] expand the protocol, if needed, so we can write dummy fcgi application (probably without real socket connection).
- [ ] write dummy fcgi Authorizer application.
- [ ] write dummy fcgi Filter application.
- [ ] test Authorizer and Filter client implementations.

**Comment by yookoala** [comment]
Closed by mistake.
